### PR TITLE
Add bufferPath to config, support bufferPath symlink

### PR DESCRIPTION
**Pull request by joshblum**
Support a user supplied path for `buffer.txt` and resolving symlinks for `buffer.txt`. Happy to make any changes if you have feedback.

### CODE REVIEW

**Comment by joshblum** [comment]
Addresses the first part of  https://github.com/heyman/heynote/issues/29

**Comment by heyman** [comment]
> Addresses the first part of https://github.com/heyman/heynote/issues/29
Yeah, I just split #29 into two issues when I saw this PR :)

**Comment by heyman** [comment]
Cool! There should also be a setting in the settings UI to allow people to select the path. But perhaps that could be a separate PR?

**Comment by joshblum** [comment]
@heyman sure thing, happy to contribute the UI in a followup.

**Comment by heyman** [comment]
Also, would if make more sense to let people specify the whole path to the buffer-file, instead of to the path of the directory?

**Comment by heyman** [comment]
When I checked out the code and started in dev mode (without having set `settings.bufferPath`)  `getBufferPath()` returns `/Users/heyman/projects/heynote/buffer-dev.txt` (i.e. the directory is CWD) instead of `/Users/heyman/Library/Application Support/buffer-dev.txt`. From looking at the code, it's not obvious to me why that is though.

**Comment by joshblum** [comment]
Ah, sorry about that, I've pushed a fix.



> Also, would if make more sense to let people specify the whole path to the buffer-file, instead of to the path of the directory?
> 
> EDIT: After some contemplation, I think I lean towards setting the directory path (your current implementation).

The more I think about it I think you were right initially, I can change the behavior to accept a path to file or directory while keeping the current defaults for both.

**Comment by heyman** [comment]
I could imagine a future where we would want to store some kind of metadata along with `buffer.txt` but as a separate file. Having the setting as a directory would make it easier to add that later if we want, so it feels more future proof. (Could also be that this is premature optimization...)

I changed so that the `realpathSync()` call is made on the whole path to the buffer file, since previously the `buffer.txt` would be overwritten in case it was a symlink.

**Comment by heyman** [comment]
@joshblum Were you interested in making a PR with the UI for the setting as well? I imagine a button that opens a directory selection dialog (found [this](https://stackoverflow.com/a/71424020/27406))

**Comment by joshblum** [comment]
@heyman sure I'll put something up

**Pull request merged**
