### PR TITLE
Support for multiple note buffers

### PR DESCRIPTION
**Pull request by heyman**
Adds support for multiple note buffers.

### CODE REVIEW

**Comment by austintreneff** [comment]
Nice, when can we expect the beta release? 👀

**Comment by heyman** [comment]
Before Christmas I hope. It's probably working fine right now, but since the new version migrates the buffer file, I want to do some more testing. 

If you're feeling adventurous you could grab a build from the artifacts of this Github Action:
https://github.com/heyman/heynote/actions/runs/12234824362

**Comment by heyman** [comment]
> Nice, when can we expect the beta release? 👀

I've released the beta version, so it should be possible to update using the built-in update function (if the you've configured Heynote to use the beta channel)

**Comment by austintreneff** [comment]
Great, thanks for the update.

**Pull request merged**
