### PR TITLE
fix: Block corruption when deleting block content using deleteLine command

### LINKED ISSUE #43: Cell corruption when deleting block contents
Selecting the contents of an entire block and pressing `CTRL + SHIFT + K` (on windows) causes the block separator and language type (e.g. `∞∞∞markdown`) to become text inside the next block and the next block's type becomes the previous block's type. See the following video:

https://github.com/heyman/heynote/assets/31131631/1d50b926-a780-4a75-9b0c-0d7fa905348b

### PR DESCRIPTION
**Pull request by Maran1947**
Resolves #43 

Solution approach [#43(comment)](https://github.com/heyman/heynote/issues/43#issuecomment-1877200618):  Implemented a custom method that is block-aware which deletes the block when running on single line within block.

### CODE REVIEW

**Comment by Maran1947** [comment]
@heyman
I've recently made updates to the pull request and would be grateful if you could take a moment to review. Your feedback is always appreciated.

**Comment by heyman** [comment]
Hi! Sorry for not having time to look at this yet.

Could you write a couple of tests? Look at `*.spec.js` files in `tests/` for examples.

**Comment by Maran1947** [comment]
I have implemented the tests. Can you please review it?

**Comment by heyman** [comment]
I think this looks good! But perhaps we could move `deleteLine` and `selectedLineBlocks` into a separate `delete-line.js` file.

**Comment by Maran1947** [comment]
Sure thing,  I'll go ahead and make that change.

**Comment by Maran1947** [comment]
Done! Moved `deleteLine` and `selectedLineBlocks` to `delete-line.js`.

**Pull request merged**
